/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvertPanel: typeof import('./src/components/workspace/AdvertPanel.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    CommentSection: typeof import('./src/components/workspace/CommentSection.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FunctionSidebar: typeof import('./src/components/workspace/FunctionSidebar.vue')['default']
    NoticeBar: typeof import('./src/components/layout/NoticeBar.vue')['default']
    PdfWorkspace: typeof import('./src/components/workspace/PdfWorkspace.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSettingsDrawer: typeof import('./src/components/settings/ThemeSettingsDrawer.vue')['default']
  }
}
